# Project GEO876 - Wildfire Mapping
Janis Büchel

### Load the API-url

In [1]:
# Install Packages:

import pandas as pd
import numpy as np
import requests
from datetime import datetime

#### Map Key and API-url

To access the API, a map key is required, which can be requested on the website.

In [2]:
#Set map key:
MAP_KEY = "e5b967caf968ec1283cb213a30e9b9d4"

# Set base url:
url = "https://firms.modaps.eosdis.nasa.gov/api/"

First step: shwo which sensors are available on the API:

In [3]:
# Create the correct API-url with the map key and show the list of sensors.
data_availability_url = f"{url}data_availability/csv/{MAP_KEY}/all"
df_data_avialiability = pd.read_csv(data_availability_url)
print("Following sensors are available:")
display(df_data_avialiability)

Following sensors are available:

             data_id    min_date    max_date
0          MODIS_NRT  2026-01-01  2026-05-03
1           MODIS_SP  2000-11-01  2025-12-31
2   VIIRS_NOAA20_NRT  2026-03-01  2026-05-03
3    VIIRS_NOAA20_SP  2018-04-01  2026-02-28
4   VIIRS_NOAA21_NRT  2024-01-17  2026-05-03
5     VIIRS_SNPP_NRT  2026-03-01  2026-05-03
6      VIIRS_SNPP_SP  2012-01-20  2026-02-28
7        LANDSAT_NRT  2022-06-20  2026-05-02
8           GOES_NRT  2022-08-09  2026-05-03
9           BA_MODIS  2000-11-01  2026-02-01
10          BA_VIIRS  2012-03-01  2026-02-01

Filter for sensors which recorded wildfired today

In [13]:
# Convert max_date into a date
df_data_avialiability["max_date"] = pd.to_datetime(df_data_avialiability['max_date'])

# Date of today
date_today = pd.Timestamp.now().normalize()
print(date_today)

# Filter for sensors with recordings today
df_available_sens = df_data_avialiability[df_data_avialiability["max_date"] == date_today]
print(df_available_sens)

# Save data_id in a list
data_id = df_available_sens["data_id"].tolist()
print(data_id)

2026-05-03 00:00:00
            data_id    min_date   max_date
0         MODIS_NRT  2026-01-01 2026-05-03
2  VIIRS_NOAA20_NRT  2026-03-01 2026-05-03
4  VIIRS_NOAA21_NRT  2024-01-17 2026-05-03
5    VIIRS_SNPP_NRT  2026-03-01 2026-05-03
8          GOES_NRT  2022-08-09 2026-05-03
['MODIS_NRT', 'VIIRS_NOAA20_NRT', 'VIIRS_NOAA21_NRT', 'VIIRS_SNPP_NRT', 'GOES_NRT']

Collect data for one sensor:

In [12]:
# Shows the data of the sensor for the desired area (world = [-180,-90,180,90]) and for the day range.
sensor = "MODIS_NRT"
focus_area = "world"
day_range = 5 # max. 5 days

area_url = f"{url}area/csv/{MAP_KEY}/{sensor}/{focus_area}/{day_range}"
df_area = pd.read_csv(area_url)

df_area

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
0,31.04159,49.40215,302.75,1.51,1.21,2026-04-29,3,Aqua,MODIS,51,6.1NRT,291.98,9.53,N
1,31.04328,49.38674,302.18,1.52,1.22,2026-04-29,3,Aqua,MODIS,47,6.1NRT,291.72,8.90,N
2,31.12479,49.33591,312.84,1.53,1.22,2026-04-29,3,Aqua,MODIS,86,6.1NRT,291.78,21.46,N
3,31.12657,49.32035,328.94,1.54,1.22,2026-04-29,3,Aqua,MODIS,100,6.1NRT,292.87,51.52,N
4,31.13726,49.32189,320.92,1.54,1.22,2026-04-29,3,Aqua,MODIS,100,6.1NRT,293.01,35.16,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26927,-2.73584,11.49613,307.54,2.08,1.40,2026-05-03,741,Terra,MODIS,51,6.1NRT,291.15,12.17,D
26928,-2.09391,15.95103,322.01,1.08,1.04,2026-05-03,741,Terra,MODIS,76,6.1NRT,296.99,14.39,D
26929,-1.28237,14.13104,318.61,1.39,1.17,2026-05-03,741,Terra,MODIS,74,6.1NRT,295.04,15.79,D
26930,-1.00437,16.00262,316.41,1.10,1.04,2026-05-03,741,Terra,MODIS,70,6.1NRT,295.11,10.64,D
26931,-8.23140,20.50896,303.44,1.52,1.22,2026-05-03,744,Terra,MODIS,20,6.1NRT,289.68,4.37,D